version: "3"
services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_enable=1 remote_host=${DOCKER_HOST_IP}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
