version: "3"
services:
    api:
        build: ./api
        ports:
          - "80:80"
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
          - ./api:/app
        depends_on:
          - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql